### ISSUE TITLE
some suggestion for you

### ISSUE THREAD

**Issue by faghiharff** [exodiver/IPTV#10]
Dear Exodiver;
I have some APIs that may help you. There are APIs of [SBS TV](https://apis.sbs.co.kr/play-api/1.0/onair/channel/S01?v_type=2&platform=pcweb&protocol=hls&ssl=Y&jwt-token=&rnd=768) and [MBC TV](http://mediaapi.imbc.com/Player/OnAirPlusURLUtil?ch=4&onairtype=1) of S.Korea.
Please make these links to direct type of m3u8, as you know we're lazy :-)
Thanks

**Comment by exodiver** [comment]
Thanks a lot!
