### ISSUE TITLE
Suggestion: Mediaset Italia from official source

### ISSUE THREAD

**Issue by irihox** [exodiver/IPTV#11]
Hi, someone on the Kodi community has figured out how to play the Mediaset channels on Kodi without issue, as if they are browsing from the official play.mediaset.it

This allows access to all Mediaset channels at max quality, including rare channels such as Boing Italia, Italia 2, 20 Mediaset, TOP Crime and La5.

Here is the code they are using:
https://github.com/kodi-bino/plugin.video.mediasetplay

I don't know how the code works, but if someone know how to make this work into a link, that would be amazing.

**Comment by exodiver** [comment]
Hi there, I would love to include them but the official mediaset channel seems to be geo restricted.

**Comment by irihox** [comment]
I was able to find the official m3u8 links, but they are Geo-restricted. Any VPN should work fine.
