### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by outcastveron** [exodiver/IPTV#12]
朋友你好
你的ytb的源是怎么抓到的？
另外有个小小的请求是否可以帮着把民视新闻给抓以下？
谢谢！

**Comment by exodiver** [comment]
可以参考这位大神的杰作:
https://github.com/ksl1989/static-m3u8

**Comment by outcastveron** [comment]
> 可以参考这位大神的杰作:
> https://github.com/ksl1989/static-m3u8

收到，谢谢！！！
