### ISSUE TITLE
希望istana分类可以加入完整的hktw的电视台

### ISSUE THREAD

**Issue by gfwfuckoff** [exodiver/IPTV#16]
为啥子突然删了一些台，我还以为是失效了😂，后来在故宫分类找到了还可以用，一新闻  年代新闻等，咋回事呢，请问可以添加回去吗？在一个英语台多的分类同时能不用切换看到港台电视，更方便，谢谢

**Comment by exodiver** [comment]
Gocast 2 的 Istana.m3u8 是本人实验性的播放文件.
