### ISSUE TITLE
Arabic TV

### ISSUE THREAD

**Issue by hassuni** [exodiver/IPTV#17]
Hallo,
if it possible to add this channels , as M3U8
the Token change everyday
Thanks a lot
here is a couple
https://shahid.mbc.net/ar/livestream/MBC5/livechannel-387937
https://shahid.mbc.net/ar/livestream/Al-Hadath/livechannel-387288
https://shahid.mbc.net/ar/livestream/MUBC-Drama/livechannel-387251
https://shahid.mbc.net/ar/livestream/MBC1/livechannel-387238
https://shahid.mbc.net/ar/livestream/Al-Arabiya/livechannel-387286
https://shahid.mbc.net/ar/livestream/MBC-Masr/livechannel-387290
https://shahid.mbc.net/ar/livestream/MBC-Masr2/livechannel-387293
https://shahid.mbc.net/ar/livestream/MBC-Iraq/livechannel-387294
**one more**
https://rotana.net/live-cinema/
https://rotana.net/live-kids/

**Comment by exodiver** [comment]
Thanks! Seems like due to the Covid 19 outbreak, they are removing the token for the time being.

Have add the MBC channels and Rotana Channels (And a few other arabic channels)

**Comment by hassuni** [comment]
thanks alot,
I will keep informed when they put the token again
