### ISSUE TITLE
Korean EPG.

### ISSUE THREAD

**Issue by oldpoem** [exodiver/IPTV#18]
I tried to run tv grab kr  batch file. Installed nodejs and npm install tv grab kr.But got error.

Any tip or instruction?   Or at least could you run cron job on korea epg?

**Comment by exodiver** [comment]
Korean EPG is now available with webgrabplus. You can check that software out.

**Comment by oldpoem** [comment]
I orginally asked on webgrabplus forum and Dev there kindly made working siteini. Thanks.
