### ISSUE TITLE
tv3 malaysia

### ISSUE THREAD

**Issue by ProjectAdrian** [exodiver/IPTV#19]
hi,
in order to get tv3 malaysia to work.. you need to add the referer as per following.

#EXTM3U 
#EXT-X-VERSION:3 
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
#EXTVLCOPT:http-referrer=https://www.dailymotion.com/embed/video/k3GVzd2cWbveXyrApah
https://stream-02.sg1.dailymotion.com/sec(g0FwEewAeL3w7b14lFp08gzI-G7iapejtFs_ruRaRYY)/dm/3/x7a7rpm/s/live-3.m3u8

**Comment by exodiver** [comment]
Thanks, but I don't think I can get the link working without connecting to a VPN Server based in Malaysia.
