### ISSUE TITLE
Iranian  Music Channel

### ISSUE THREAD

**Issue by hassuni** [exodiver/IPTV#20]
Hello,
Can you please add this Channel.
thanks for all the help.
https://bittube.tv/playerembed/12067/BRJfxvDlyaXTF3GrxB1i
or from
https://www.pmc.tv/

**Comment by faghiharff** [comment]
http://51.15.139.108/hls/stream.m3u8

**Comment by faghiharff** [comment]
> Hello,
> Can you please add this Channel.
> thanks for all the help.
> https://bittube.tv/playerembed/12067/BRJfxvDlyaXTF3GrxB1i
> or from
> https://www.pmc.tv/

you can use this m3u8 on your player:
http://51.15.139.108/hls/stream.m3u8

**Comment by hassuni** [comment]
@faghiharff 
thanks

**Comment by exodiver** [comment]
Thanks faghiharff for helping!
