### ISSUE TITLE
德国之声英语台的epg是德语台对应的预告

### ISSUE THREAD

**Issue by gfwfuckoff** [exodiver/IPTV#22]
抓取错了，忘修正，谢谢

**Comment by gfwfuckoff** [comment]
nhk world also wrong channel for the epg

**Comment by gfwfuckoff** [comment]
现在dw eng的源只有声音，没有图像黑屏了

**Comment by exodiver** [comment]
> nhk world also wrong channel for the epg

The epg NHK world is taken from the NHK website. I chose the Japanese language version.

**Comment by exodiver** [comment]
> 现在dw eng的源只有声音，没有图像黑屏了

谢谢您的提醒, 我会查的

**Comment by gfwfuckoff** [comment]
@exodiver 能否抓取对应的epg呢，应该是改个参数就行吧，我不太懂😂，英语台就抓eng的版本呗

**Comment by gfwfuckoff** [comment]
另外 pbs America的源没有问题的啊，咋移除节目源和对应epg了呢

**Comment by gfwfuckoff** [comment]
da vinci in learning group Too disappear
