### ISSUE TITLE
Indian uk channels 

### ISSUE THREAD

**Issue by naz75** [exodiver/IPTV#23]
Hi everyone anybody have m3u8 Indian UK channels

**Comment by pgebbon** [comment]
#EXTINF:-1 tvg-logo="https://i.imgur.com/bZ5JEtN.png" group-title="Tamil Christian TV",My Jesus TV
http://clicklivestream.net:1935/live/mjtv/mjtv/playlist.m3u8

**Comment by exodiver** [comment]
> #EXTINF:-1 tvg-logo="https://i.imgur.com/bZ5JEtN.png" group-title="Tamil Christian TV",My Jesus TV
> http://clicklivestream.net:1935/live/mjtv/mjtv/playlist.m3u8

Thanks
