### ISSUE TITLE
TVN not working

### ISSUE THREAD

**Issue by Nkidz** [exodiver/IPTV#44]
Is it possible to make tvN working? Just curious because ive got error for that channel

Thanks in advance

**Comment by exodiver** [comment]
> Is it possible to make tvN working? Just curious because ive got error for that channel
> 
> Thanks in advance

The only working TvN link requires a player and device that supports Widevine 1 (aka Netflix Certified) as it is a drm link. Very sorry all the non drm version of the channel is gone.
